# env.zsh — environment variables and directory bootstrapping

# Keep PATH/FPATH/MANPATH free of duplicates. Without this, every `exec zsh`
# (and our `reload` alias) re-appends the same dirs, growing PATH unbounded.
# Must run BEFORE any path+= below so dedup applies as entries are added.
typeset -gU path fpath manpath PATH FPATH MANPATH

# ── XDG directories ──────────────────────────────────────────────────────────
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

# ── local bin / man / completions ────────────────────────────────────────────
BIN_DIR=~/.local/bin
COMP_DIR=~/.local/share/zsh/completions
MAN_DIR=~/.local/man

for _dir in "$BIN_DIR" "$COMP_DIR" "$MAN_DIR" "${XDG_CACHE_HOME}/zsh"; do
  [[ -d $_dir ]] || mkdir -p "$_dir"
done
unset _dir

path+=("$BIN_DIR")
[[ -d "$HOME/.cargo/bin" ]] && path+=("$HOME/.cargo/bin")
[[ -d "$HOME/gopath/bin" ]] && path+=("$HOME/gopath/bin")
[[ -d "$HOME/.claude/bin" ]] && path+=("$HOME/.claude/bin")
# bun — global package bin (omp etc.); bun keeps it under XDG cache here
[[ -d "$HOME/.cache/.bun/bin" ]] && path+=("$HOME/.cache/.bun/bin")
# krew — kubectl plugin manager. Plugins install as kubectl-<name> binaries
# here and run as `kubectl <name>` (ctx, ns, stern, tree, neat, popeye, …).
[[ -d "${KREW_ROOT:-$HOME/.krew}/bin" ]] && path+=("${KREW_ROOT:-$HOME/.krew}/bin")
fpath+=("$COMP_DIR")
manpath+=("$MAN_DIR")

# ── language toolchains ──────────────────────────────────────────────────────
[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"
export GOPATH="${HOME}/gopath"

# ── history ──────────────────────────────────────────────────────────────────
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE="${XDG_CACHE_HOME}/zsh-history"

# keep stray tool histories out of ~ (XDG hygiene, 2026-07-07)
export LESSHISTFILE="${XDG_CACHE_HOME}/lesshst"
export NODE_REPL_HISTORY=""   # off — never useful, always clutter

# ── browser — route WSL URL opens to the Windows default browser ────────────
# wslview (from wslu) is the standard tool: it calls the Windows shell default
# browser handler via WSL interop, no X11/Wayland involved. Tools that respect
# $BROWSER (xdg-open, gsutil, poetry, etc.) get this; xdg-open itself is also
# overridden to wslview so hard-coded `xdg-open` callers go the right way.
if [[ -n ${WSL_DISTRO_NAME:-} ]] && has wslview; then
  export BROWSER="wslview"
  # xdg-open → wslview shim: many tools hard-code xdg-open instead of $BROWSER.
  # Shadow it with a function so those callers also reach the Windows browser.
  xdg-open() { wslview "$@"; }
fi

# ── editor — prefer host Zed on WSL, then Linux Zed, fall back gracefully ────
if [[ -n ${WSL_DISTRO_NAME:-} ]] && has zedw; then
  # Windows-host Zed via WSL remoting (bin/zedw). EDITOR is NON-blocking so a
  # stray editor-open (e.g. `starship config`) doesn't freeze the pane; only the
  # tools that must read the file back get --wait. Off-WSL this branch is skipped.
  export EDITOR="zedw"
  export GIT_EDITOR="zedw --wait"
  export KUBE_EDITOR="zedw --wait"
  # crontab -e / visudo use bare $EDITOR and need blocking — run those as:
  #   EDITOR='zedw --wait' crontab -e
elif has zed; then
  ZED_BIN="$(which zed)"
  export EDITOR="$ZED_BIN"              # non-blocking (matches the `code` branch)
  export GIT_EDITOR="$ZED_BIN --wait"
  export KUBE_EDITOR="$ZED_BIN --wait"

  # sudoedit with Zed (must block so sudo can install the edited file)
  suzed() { EDITOR="$ZED_BIN --wait" command -- sudo -e "$@"; }
elif has code; then
  VSCODE_BIN="$(which code)"
  export EDITOR="$VSCODE_BIN"
  export KUBE_EDITOR="$VSCODE_BIN -w"
  export GIT_EDITOR="$VSCODE_BIN -w"

  sucode() { EDITOR="$VSCODE_BIN -w" command -- sudo -e "$@"; }
elif has nvim; then
  export EDITOR=nvim
elif has vim; then
  export EDITOR=vim
elif has emacs; then
  export EDITOR=emacs
elif has nano; then
  printf "${RED}WARNING:${NO_COLOR} falling back to nano. Install a real editor.\n"
  export EDITOR=nano
fi

# ── misc ─────────────────────────────────────────────────────────────────────
export CLICOLOR_FORCE=1
export KEYTIMEOUT=1
export LIBRARY_LOG_TIMESTAMP=1
export PAGER="less -RF"

# bashcompinit — needed for `complete -C` style completions (vault, terraform).
# Init once here (the first module that needs it); later users just call `complete`.
(( $+functions[compdef] )) && (( ! $+functions[complete] )) && { autoload -U +X bashcompinit && bashcompinit; }

# vault completion (requires vault binary in BIN_DIR)
[[ -x "${BIN_DIR}/vault" ]] && complete -o nospace -C "${BIN_DIR}/vault" vault

# ── modern tool init ─────────────────────────────────────────────────────────

# Theme palette — generated by `theme set <name>` (starship/scripts/theme).
# Exports THEME_FZF_COLORS / THEME_FZFTAB_COLORS / THEME_HSS_* consumed below
# and in plugins.zsh, so fzf + fzf-tab + history-search match the active theme.
[[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/theme.zsh" ]] && \
  source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/theme.zsh"

# zoxide — smart cd (`z foo` jumps to the most-frecent dir matching `foo`)
# Adds `z`, `zi` (fzf-interactive), and hooks chpwd to track dir frecency.
has zoxide && eval "$(zoxide init zsh)"

# fzf — fuzzy finder key bindings + completion
# Ctrl-R → history fzf, Ctrl-T → file fzf, Alt-C → cd fzf
# (atuin overrides Ctrl-R if also enabled below.)
if has fzf; then
  # Key bindings + completion — XDG path on brew, fallback to legacy
  if [[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/fzf/fzf.zsh" ]]; then
    source "${XDG_CONFIG_HOME:-$HOME/.config}/fzf/fzf.zsh"
  elif [[ -f ~/.fzf.zsh ]]; then
    source ~/.fzf.zsh
  fi
  # FZF colors come from the active theme (THEME_FZF_COLORS, set above). Falls
  # back to a neutral spec if no theme has been generated yet.
  export FZF_DEFAULT_OPTS="
    --height 60% --layout=reverse --border --ansi
    --color=${THEME_FZF_COLORS:-fg:-1,bg:-1,hl:cyan,fg+:-1,bg+:-1,hl+:cyan}
    --prompt='▸ ' --pointer='▲' --marker='◉'
  "
  # Use fd for file+dir listings if available (respects .gitignore, fast)
  if has fd; then
    export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
  fi

  # Ctrl-R history search — multi-line preview, dedup on press, no sort toggle
  # (prefer most recent → most frequent via HISTORY_IGNORE is already set)
  export FZF_CTRL_R_OPTS="
    --preview 'echo {}' --preview-window down:3:hidden:wrap
    --bind 'ctrl-/:toggle-preview'
    --bind 'ctrl-y:execute-silent(echo -n {2..} | ~/.local/bin/tmux-copy)+abort'
    --color header:italic
    --header 'ctrl-/ preview · ctrl-y copy · enter run'
  "

  # Ctrl-T file picker — preview with bat if available, else cat
  if has bat; then
    export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range=:200 {}'"
  else
    export FZF_CTRL_T_OPTS="--preview 'head -200 {}'"
  fi

  # Alt-C directory picker — tree preview
  export FZF_ALT_C_OPTS="--preview 'ls -la --color=always {} | head -40'"

  # Inside tmux, use a popup instead of the full-screen takeover
  [[ -n $TMUX ]] && export FZF_TMUX_OPTS='-p 85%,70%'
fi

# bat — cat replacement with syntax highlighting
if has bat; then
  export BAT_THEME="OneHalfDark"
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

# delta — git diff viewer (configured in ~/.gitconfig, this just ensures
# the binary is discoverable)
# (delta is used via git's [core] pager — no env var needed here)

# proto — multi-language toolchain manager (node/pnpm/bun/python/moon; replaces fnm+nvm).
# Single source of truth for tool versions (matches the `agentic` monorepo's .prototools).
# `proto activate` puts shims on PATH and auto-switches pinned versions on cd into dirs
# with .prototools (and legacy .nvmrc/.node-version). Migrated off fnm 2026-07-25.
if has proto; then
  eval "$(proto activate zsh)"
fi

# rust — cargo + rustup binaries live in ~/.cargo/bin (added once above; the
# typeset -gU at the top of this file collapses any re-adds, so no append here).

# uv — Astral's Python toolchain (pip/pipx/venv/pyenv replacement)
# Completion only — binary lives in /opt/homebrew/bin
has uv && eval "$(uv generate-shell-completion zsh 2>/dev/null)"

# direnv — per-directory env vars via .envrc
# Hook into chpwd to auto-load/unload on cd. `direnv allow` to whitelist a dir.
has direnv && eval "$(direnv hook zsh)"

# atuin — sqlite-backed shell history with fuzzy/contextual search
# Replaces Ctrl-R. Run `atuin register` or `atuin login` once to enable sync.
# Use `atuin import auto` to seed from existing zsh history.
if has atuin; then
  eval "$(atuin init zsh --disable-up-arrow)"
fi

# bun — completions (binary on PATH via brew)
[[ -s "$HOME/.bun/_bun" ]] && source "$HOME/.bun/_bun"

# starship prompt — keep near end of env setup so it's the final PROMPT owner
has starship && eval "$(starship init zsh)"
